"""simple book model

Revision ID: 627993176927
Revises: 
Create Date: 2021-10-24 23:32:10.870789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627993176927'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simple_book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simple_book')
    # ### end Alembic commands ###
